name: Build
on:
  pull_request:
    branches: [master, develop]

jobs:
  on_linux_win:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"

      - name: build
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          id
          yarn app-linux
          echo "finished linux"
          chown -R root:root /github/home
          yarn app-windows
          echo "finished windows"
          ls -la dist
  on_mac:
    runs-on: macos-11
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"

      - name: build
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
          OTHER_CODE_SIGN_FLAGS: "--options=runtime --timestamp"
          PYTHON_PATH: "/usr/bin/python2"
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8
          yarn config set network-timeout 300000
          yarn app-macos
          ls -la dist
