name: Test
on:
  pull_request:
    branches: [master, develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"
      - name: Test testing mode is 'false' in settings.json
        run: |
          ps -p $$
          jq --version
          MERCURY_WALLET_TESTING_MODE=`jq .testing_mode src/settings.json`
          if [ $MERCURY_WALLET_TESTING_MODE != false ]; then exit 1; fi
      - run: sed -i -e 's/false/true/g' src/settings.json
      - run: npm install --force
      - run: yarn test
  e2e-tests:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          uses: actions/setup-node@v3
          with:
            node-version: "16.16"
        - run: npm install --force
        - name: Start local server
          run: npm run web & # Start the server in the background
        - name: Wait for server to be up
          run: |
            timeout=300 # Set the timeout value in seconds
            until nc -z localhost 3000; do
              echo "Waiting for server to be up..."
              sleep 5
              ((timeout--))
              if [ $timeout -le 0 ]; then
                echo "Timeout reached. Exiting."
                exit 1
              fi
            done
        - name: Run e2e tests
          uses: cypress-io/github-action@v5
          with:
            browser: chrome
            install: false
